name: Super-Linter

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Run Super Linter (for HTML, CSS, JS)
      - name: Run Super Linter
        uses: github/super-linter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for access
          VALIDATE_HTML: true
          VALIDATE_CSS: true
          VALIDATE_JAVASCRIPT: true
          VALIDATE_ALL_CODEBASE: false  # Only validate changed/edited files
          # Explicitly disabling linters that we won't be utilizing
          VALIDATE_SQL: false
          VALIDATE_PYTHON: false
          VALIDATE_MARKDOWN: false
          VALIDATE_YAML: false
          VALIDATE_JSON: false
          VALIDATE_DOCKERFILE: false
