name: Super-Linter

on:
  # Run the workflow for pushes to any branch and pull requests to any branch
  push:
    branches:
      - "**" # This wildcard matches any branch
  pull_request:
    branches:
      - "**" # This will run for pull requests to any branch

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Run Super Linter
      - name: Run Super Linter
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false  # Only validate changed/edited files
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for access
          
          # Enable linters for HTML, CSS, and JS
          VALIDATE_HTML: true
          VALIDATE_CSS: true
          VALIDATE_JAVASCRIPT: true
          
          # Explicitly disable other linters (including SQL)
          VALIDATE_SQL: false
          VALIDATE_PYTHON: false
          VALIDATE_MARKDOWN: false
          VALIDATE_YAML: false
          VALIDATE_JSON: false
          VALIDATE_DOCKERFILE: false