name: Super-Linter

on:
  # Run the workflow for pushes to any branch and pull requests to any branch
  push:
    branches:
      - "**" # This wildcard matches any branch
  pull_request:
    branches:
      - "**" # This will run for pull requests to any branch

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Python and create a virtual environment
      - name: Set up Python and Install SQLFluff
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python3 -m pip install --upgrade pip
          pip install sqlfluff

      # Run SQLFluff linter in the virtual environment
      - name: Run SQLFluff linter
        run: |
          source venv/bin/activate
          sqlfluff lint db/schema.sql --dialect mysql
          sqlfluff lint db/seed.sql --dialect mysql

      # Run Super Linter
      - name: Run Super Linter
        uses: github/super-linter@v5
        env:
          DEFAULT_BRANCH: main # Set the default branch for Super Linter's configuration
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Provide GitHub token for API access
